### ISSUE TITLE
Avoid error when deleting configuration that is already empty

### ISSUE THREAD

**Issue by ArndalAndersen** [psyfood/pyqmix#61]
If the configuration has not been specified, i.e. the config is empty:
``` python
config.read_config()
```
, then running:   
``` python 
config.delete_config()
``` 
produces an error.
It would be more intuitive if there was no such error and the config was just left empty.

**Comment by hoechenberger** [comment]
Want to try a fix? I believe you just need to wrap the `os.remove()` call into a `try/except` block like the one below:

https://github.com/psyfood/pyqmix/blob/30bbc33be910bcd8beef2b0062e80865c8e14934/pyqmix/config.py#L63
